[package]
name = "check_rungrep"
version = "0.1.0"
edition = "2021"
rust-version = "1.75.0"
license = "GPL-3.0"
authors = ["Alexander A. Klimov <a@kli.mov>"]

[dependencies]
humantime = "2.3.0"
memchr = "2.7.6"
nagios-range = "0.2.5"
regex = "1.11.2"
